-- Jack Goyette, Spencer Schurk
-- jgoyette@calpoly.edu, sschurk@calpoly.edu

DROP TABLE CARMAKERS;

DROP TABLE CARNAMES;

DROP TABLE CARSDATA;

DROP TABLE CONTINENTS;

DROP TABLE COUNTRIES;

DROP TABLE MODELLIST;