-- Jack Goyette, Spencer Schurk
-- jgoyette@calpoly.edu, sschurk@calpoly.edu

INSERT INTO CARNAMES VALUES(1,'chevrolet','chevrolet chevelle malibu');
INSERT INTO CARNAMES VALUES(2,'buick','buick skylark 320');
INSERT INTO CARNAMES VALUES(3,'plymouth','plymouth satellite');
INSERT INTO CARNAMES VALUES(4,'amc','amc rebel sst');
INSERT INTO CARNAMES VALUES(5,'ford','ford torino');
INSERT INTO CARNAMES VALUES(6,'ford','ford galaxie 500');
INSERT INTO CARNAMES VALUES(7,'chevrolet','chevrolet impala');
INSERT INTO CARNAMES VALUES(8,'plymouth','plymouth fury iii');
INSERT INTO CARNAMES VALUES(9,'pontiac','pontiac catalina');
INSERT INTO CARNAMES VALUES(10,'amc','amc ambassador dpl');
INSERT INTO CARNAMES VALUES(11,'citroen','citroen ds-21 pallas');
INSERT INTO CARNAMES VALUES(12,'chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO CARNAMES VALUES(13,'ford','ford torino (sw)');
INSERT INTO CARNAMES VALUES(14,'plymouth','plymouth satellite (sw)');
INSERT INTO CARNAMES VALUES(15,'amc','amc rebel sst (sw)');
INSERT INTO CARNAMES VALUES(16,'dodge','dodge challenger se');
INSERT INTO CARNAMES VALUES(17,'plymouth','plymouth cuda 340');
INSERT INTO CARNAMES VALUES(18,'ford','ford mustang boss 302');
INSERT INTO CARNAMES VALUES(19,'chevrolet','chevrolet monte carlo');
INSERT INTO CARNAMES VALUES(20,'buick','buick estate wagon (sw)');
INSERT INTO CARNAMES VALUES(21,'toyota','toyota corona mark ii');
INSERT INTO CARNAMES VALUES(22,'plymouth','plymouth duster');
INSERT INTO CARNAMES VALUES(23,'amc','amc hornet');
INSERT INTO CARNAMES VALUES(24,'ford','ford maverick');
INSERT INTO CARNAMES VALUES(25,'datsun','datsun pl510');
INSERT INTO CARNAMES VALUES(26,'volkswagen','volkswagen 1131 deluxe sedan');
INSERT INTO CARNAMES VALUES(27,'peugeot','peugeot 504');
INSERT INTO CARNAMES VALUES(28,'audi','audi 100 ls');
INSERT INTO CARNAMES VALUES(29,'saab','saab 99e');
INSERT INTO CARNAMES VALUES(30,'bmw','bmw 2002');
INSERT INTO CARNAMES VALUES(31,'amc','amc gremlin');
INSERT INTO CARNAMES VALUES(32,'ford','ford f250');
INSERT INTO CARNAMES VALUES(33,'chevrolet','chevy c20');
INSERT INTO CARNAMES VALUES(34,'dodge','dodge d200');
INSERT INTO CARNAMES VALUES(35,'hi','hi 1200d');
INSERT INTO CARNAMES VALUES(36,'datsun','datsun pl510');
INSERT INTO CARNAMES VALUES(37,'chevrolet','chevrolet vega 2300');
INSERT INTO CARNAMES VALUES(38,'toyota','toyota corona');
INSERT INTO CARNAMES VALUES(39,'ford','ford pinto');
INSERT INTO CARNAMES VALUES(40,'volkswagen','volkswagen super beetle 117');
INSERT INTO CARNAMES VALUES(41,'amc','amc gremlin');
INSERT INTO CARNAMES VALUES(42,'plymouth','plymouth satellite custom');
INSERT INTO CARNAMES VALUES(43,'chevrolet','chevrolet chevelle malibu');
INSERT INTO CARNAMES VALUES(44,'ford','ford torino 500');
INSERT INTO CARNAMES VALUES(45,'amc','amc matador');
INSERT INTO CARNAMES VALUES(46,'chevrolet','chevrolet impala');
INSERT INTO CARNAMES VALUES(47,'pontiac','pontiac catalina brougham');
INSERT INTO CARNAMES VALUES(48,'ford','ford galaxie 500');
INSERT INTO CARNAMES VALUES(49,'plymouth','plymouth fury iii');
INSERT INTO CARNAMES VALUES(50,'dodge','dodge monaco (sw)');
INSERT INTO CARNAMES VALUES(51,'ford','ford country squire (sw)');
INSERT INTO CARNAMES VALUES(52,'pontiac','pontiac safari (sw)');
INSERT INTO CARNAMES VALUES(53,'amc','amc hornet sportabout (sw)');
INSERT INTO CARNAMES VALUES(54,'chevrolet','chevrolet vega (sw)');
INSERT INTO CARNAMES VALUES(55,'pontiac','pontiac firebird');
INSERT INTO CARNAMES VALUES(56,'ford','ford mustang');
INSERT INTO CARNAMES VALUES(57,'mercury','mercury capri 2000');
INSERT INTO CARNAMES VALUES(58,'opel','opel 1900');
INSERT INTO CARNAMES VALUES(59,'peugeot','peugeot 304');
INSERT INTO CARNAMES VALUES(60,'fiat','fiat 124b');
INSERT INTO CARNAMES VALUES(61,'toyota','toyota corolla 1200');
INSERT INTO CARNAMES VALUES(62,'datsun','datsun 1200');
INSERT INTO CARNAMES VALUES(63,'volkswagen','volkswagen model 111');
INSERT INTO CARNAMES VALUES(64,'plymouth','plymouth cricket');
INSERT INTO CARNAMES VALUES(65,'toyota','toyota corona hardtop');
INSERT INTO CARNAMES VALUES(66,'dodge','dodge colt hardtop');
INSERT INTO CARNAMES VALUES(67,'volkswagen','volkswagen type 3');
INSERT INTO CARNAMES VALUES(68,'chevrolet','chevrolet vega');
INSERT INTO CARNAMES VALUES(69,'ford','ford pinto runabout');
INSERT INTO CARNAMES VALUES(70,'chevrolet','chevrolet impala');
INSERT INTO CARNAMES VALUES(71,'pontiac','pontiac catalina');
INSERT INTO CARNAMES VALUES(72,'plymouth','plymouth fury iii');
INSERT INTO CARNAMES VALUES(73,'ford','ford galaxie 500');
INSERT INTO CARNAMES VALUES(74,'amc','amc ambassador sst');
INSERT INTO CARNAMES VALUES(75,'mercury','mercury marquis');
INSERT INTO CARNAMES VALUES(76,'buick','buick lesabre custom');
INSERT INTO CARNAMES VALUES(77,'oldsmobile','oldsmobile delta 88 royale');
INSERT INTO CARNAMES VALUES(78,'chrysler','chrysler newport royal');
INSERT INTO CARNAMES VALUES(79,'mazda','mazda rx2 coupe');
INSERT INTO CARNAMES VALUES(80,'amc','amc matador (sw)');
INSERT INTO CARNAMES VALUES(81,'chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO CARNAMES VALUES(82,'ford','ford gran torino (sw)');
INSERT INTO CARNAMES VALUES(83,'plymouth','plymouth satellite custom (sw)');
INSERT INTO CARNAMES VALUES(84,'volvo','volvo 145e (sw)');
INSERT INTO CARNAMES VALUES(85,'volkswagen','volkswagen 411 (sw)');
INSERT INTO CARNAMES VALUES(86,'peugeot','peugeot 504 (sw)');
INSERT INTO CARNAMES VALUES(87,'renault','renault 12 (sw)');
INSERT INTO CARNAMES VALUES(88,'ford','ford pinto (sw)');
INSERT INTO CARNAMES VALUES(89,'datsun','datsun 510 (sw)');
INSERT INTO CARNAMES VALUES(90,'toyota','toyota corona mark ii (sw)');
INSERT INTO CARNAMES VALUES(91,'dodge','dodge colt (sw)');
INSERT INTO CARNAMES VALUES(92,'toyota','toyota corolla 1600 (sw)');
INSERT INTO CARNAMES VALUES(93,'buick','buick century 350');
INSERT INTO CARNAMES VALUES(94,'amc','amc matador');
INSERT INTO CARNAMES VALUES(95,'chevrolet','chevrolet malibu');
INSERT INTO CARNAMES VALUES(96,'ford','ford gran torino');
INSERT INTO CARNAMES VALUES(97,'dodge','dodge coronet custom');
INSERT INTO CARNAMES VALUES(98,'mercury','mercury marquis brougham');
INSERT INTO CARNAMES VALUES(99,'chevrolet','chevrolet caprice classic');
INSERT INTO CARNAMES VALUES(100,'ford','ford ltd');
INSERT INTO CARNAMES VALUES(101,'plymouth','plymouth fury gran sedan');
INSERT INTO CARNAMES VALUES(102,'chrysler','chrysler new yorker brougham');
INSERT INTO CARNAMES VALUES(103,'buick','buick electra 225 custom');
INSERT INTO CARNAMES VALUES(104,'amc','amc ambassador brougham');
INSERT INTO CARNAMES VALUES(105,'plymouth','plymouth valiant');
INSERT INTO CARNAMES VALUES(106,'chevrolet','chevrolet nova custom');
INSERT INTO CARNAMES VALUES(107,'amc','amc hornet');
INSERT INTO CARNAMES VALUES(108,'ford','ford maverick');
INSERT INTO CARNAMES VALUES(109,'plymouth','plymouth duster');
INSERT INTO CARNAMES VALUES(110,'volkswagen','volkswagen super beetle');
INSERT INTO CARNAMES VALUES(111,'chevrolet','chevrolet impala');
INSERT INTO CARNAMES VALUES(112,'ford','ford country');
INSERT INTO CARNAMES VALUES(113,'plymouth','plymouth custom suburb');
INSERT INTO CARNAMES VALUES(114,'oldsmobile','oldsmobile vista cruiser');
INSERT INTO CARNAMES VALUES(115,'amc','amc gremlin');
INSERT INTO CARNAMES VALUES(116,'toyota','toyota carina');
INSERT INTO CARNAMES VALUES(117,'chevrolet','chevrolet vega');
INSERT INTO CARNAMES VALUES(118,'datsun','datsun 610');
INSERT INTO CARNAMES VALUES(119,'mazda','mazda rx3');
INSERT INTO CARNAMES VALUES(120,'ford','ford pinto');
INSERT INTO CARNAMES VALUES(121,'mercury','mercury capri v6');
INSERT INTO CARNAMES VALUES(122,'fiat','fiat 124 sport coupe');
INSERT INTO CARNAMES VALUES(123,'chevrolet','chevrolet monte carlo s');
INSERT INTO CARNAMES VALUES(124,'pontiac','pontiac grand prix');
INSERT INTO CARNAMES VALUES(125,'fiat','fiat 128');
INSERT INTO CARNAMES VALUES(126,'opel','opel manta');
INSERT INTO CARNAMES VALUES(127,'audi','audi 100ls');
INSERT INTO CARNAMES VALUES(128,'volvo','volvo 144ea');
INSERT INTO CARNAMES VALUES(129,'dodge','dodge dart custom');
INSERT INTO CARNAMES VALUES(130,'saab','saab 99le');
INSERT INTO CARNAMES VALUES(131,'toyota','toyota mark ii');
INSERT INTO CARNAMES VALUES(132,'oldsmobile','oldsmobile omega');
INSERT INTO CARNAMES VALUES(133,'plymouth','plymouth duster');
INSERT INTO CARNAMES VALUES(134,'ford','ford maverick');
INSERT INTO CARNAMES VALUES(135,'amc','amc hornet');
INSERT INTO CARNAMES VALUES(136,'chevrolet','chevrolet nova');
INSERT INTO CARNAMES VALUES(137,'datsun','datsun b210');
INSERT INTO CARNAMES VALUES(138,'ford','ford pinto');
INSERT INTO CARNAMES VALUES(139,'toyota','toyota corolla 1200');
INSERT INTO CARNAMES VALUES(140,'chevrolet','chevrolet vega');
INSERT INTO CARNAMES VALUES(141,'chevrolet','chevrolet chevelle malibu classic');
INSERT INTO CARNAMES VALUES(142,'amc','amc matador');
INSERT INTO CARNAMES VALUES(143,'plymouth','plymouth satellite sebring');
INSERT INTO CARNAMES VALUES(144,'ford','ford gran torino');
INSERT INTO CARNAMES VALUES(145,'buick','buick century luxus (sw)');
INSERT INTO CARNAMES VALUES(146,'dodge','dodge coronet custom (sw)');
INSERT INTO CARNAMES VALUES(147,'ford','ford gran torino (sw)');
INSERT INTO CARNAMES VALUES(148,'amc','amc matador (sw)');
INSERT INTO CARNAMES VALUES(149,'audi','audi fox');
INSERT INTO CARNAMES VALUES(150,'volkswagen','volkswagen dasher');
INSERT INTO CARNAMES VALUES(151,'opel','opel manta');
INSERT INTO CARNAMES VALUES(152,'toyota','toyota corona');
INSERT INTO CARNAMES VALUES(153,'datsun','datsun 710');
INSERT INTO CARNAMES VALUES(154,'dodge','dodge colt');
INSERT INTO CARNAMES VALUES(155,'fiat','fiat 128');
INSERT INTO CARNAMES VALUES(156,'fiat','fiat 124 tc');
INSERT INTO CARNAMES VALUES(157,'honda','honda civic');
INSERT INTO CARNAMES VALUES(158,'subaru','subaru');
INSERT INTO CARNAMES VALUES(159,'fiat','fiat x1.9');
INSERT INTO CARNAMES VALUES(160,'plymouth','plymouth valiant custom');
INSERT INTO CARNAMES VALUES(161,'chevrolet','chevrolet nova');
INSERT INTO CARNAMES VALUES(162,'mercury','mercury monarch');
INSERT INTO CARNAMES VALUES(163,'ford','ford maverick');
INSERT INTO CARNAMES VALUES(164,'pontiac','pontiac catalina');
INSERT INTO CARNAMES VALUES(165,'chevrolet','chevrolet bel air');
INSERT INTO CARNAMES VALUES(166,'plymouth','plymouth grand fury');
INSERT INTO CARNAMES VALUES(167,'ford','ford ltd');
INSERT INTO CARNAMES VALUES(168,'buick','buick century');
INSERT INTO CARNAMES VALUES(169,'chevrolet','chevrolet chevelle malibu');
INSERT INTO CARNAMES VALUES(170,'amc','amc matador');
INSERT INTO CARNAMES VALUES(171,'plymouth','plymouth fury');
INSERT INTO CARNAMES VALUES(172,'buick','buick skyhawk');
INSERT INTO CARNAMES VALUES(173,'chevrolet','chevrolet monza 2+2');
INSERT INTO CARNAMES VALUES(174,'ford','ford mustang ii');
INSERT INTO CARNAMES VALUES(175,'toyota','toyota corolla');
INSERT INTO CARNAMES VALUES(176,'ford','ford pinto');
INSERT INTO CARNAMES VALUES(177,'amc','amc gremlin');
INSERT INTO CARNAMES VALUES(178,'pontiac','pontiac astro');
INSERT INTO CARNAMES VALUES(179,'toyota','toyota corona');
INSERT INTO CARNAMES VALUES(180,'volkswagen','volkswagen dasher');
INSERT INTO CARNAMES VALUES(181,'datsun','datsun 710');
INSERT INTO CARNAMES VALUES(182,'ford','ford pinto');
INSERT INTO CARNAMES VALUES(183,'volkswagen','volkswagen rabbit');
INSERT INTO CARNAMES VALUES(184,'amc','amc pacer');
INSERT INTO CARNAMES VALUES(185,'audi','audi 100ls');
INSERT INTO CARNAMES VALUES(186,'peugeot','peugeot 504');
INSERT INTO CARNAMES VALUES(187,'volvo','volvo 244dl');
INSERT INTO CARNAMES VALUES(188,'saab','saab 99le');
INSERT INTO CARNAMES VALUES(189,'honda','honda civic cvcc');
INSERT INTO CARNAMES VALUES(190,'fiat','fiat 131');
INSERT INTO CARNAMES VALUES(191,'opel','opel 1900');
INSERT INTO CARNAMES VALUES(192,'capri','capri ii');
INSERT INTO CARNAMES VALUES(193,'dodge','dodge colt');
INSERT INTO CARNAMES VALUES(194,'renault','renault 12tl');
INSERT INTO CARNAMES VALUES(195,'chevrolet','chevrolet chevelle malibu classic');
INSERT INTO CARNAMES VALUES(196,'dodge','dodge coronet brougham');
INSERT INTO CARNAMES VALUES(197,'amc','amc matador');
INSERT INTO CARNAMES VALUES(198,'ford','ford gran torino');
INSERT INTO CARNAMES VALUES(199,'plymouth','plymouth valiant');
INSERT INTO CARNAMES VALUES(200,'chevrolet','chevrolet nova');
INSERT INTO CARNAMES VALUES(201,'ford','ford maverick');
INSERT INTO CARNAMES VALUES(202,'amc','amc hornet');
INSERT INTO CARNAMES VALUES(203,'chevrolet','chevrolet chevette');
INSERT INTO CARNAMES VALUES(204,'chevrolet','chevrolet woody');
INSERT INTO CARNAMES VALUES(205,'volkswagen','vw rabbit');
INSERT INTO CARNAMES VALUES(206,'honda','honda civic');
INSERT INTO CARNAMES VALUES(207,'dodge','dodge aspen se');
INSERT INTO CARNAMES VALUES(208,'ford','ford granada ghia');
INSERT INTO CARNAMES VALUES(209,'pontiac','pontiac ventura sj');
INSERT INTO CARNAMES VALUES(210,'amc','amc pacer d/l');
INSERT INTO CARNAMES VALUES(211,'volkswagen','volkswagen rabbit');
INSERT INTO CARNAMES VALUES(212,'datsun','datsun b-210');
INSERT INTO CARNAMES VALUES(213,'toyota','toyota corolla');
INSERT INTO CARNAMES VALUES(214,'ford','ford pinto');
INSERT INTO CARNAMES VALUES(215,'volvo','volvo 245');
INSERT INTO CARNAMES VALUES(216,'plymouth','plymouth volare premier v8');
INSERT INTO CARNAMES VALUES(217,'peugeot','peugeot 504');
INSERT INTO CARNAMES VALUES(218,'toyota','toyota mark ii');
INSERT INTO CARNAMES VALUES(219,'mercedes-benz','mercedes-benz 280s');
INSERT INTO CARNAMES VALUES(220,'cadillac','cadillac seville');
INSERT INTO CARNAMES VALUES(221,'chevrolet','chevy c10');
INSERT INTO CARNAMES VALUES(222,'ford','ford f108');
INSERT INTO CARNAMES VALUES(223,'dodge','dodge d100');
INSERT INTO CARNAMES VALUES(224,'honda','honda accord cvcc');
INSERT INTO CARNAMES VALUES(225,'buick','buick opel isuzu deluxe');
INSERT INTO CARNAMES VALUES(226,'renault','renault 5 gtl');
INSERT INTO CARNAMES VALUES(227,'plymouth','plymouth arrow gs');
INSERT INTO CARNAMES VALUES(228,'datsun','datsun f-10 hatchback');
INSERT INTO CARNAMES VALUES(229,'chevrolet','chevrolet caprice classic');
INSERT INTO CARNAMES VALUES(230,'oldsmobile','oldsmobile cutlass supreme');
INSERT INTO CARNAMES VALUES(231,'dodge','dodge monaco brougham');
INSERT INTO CARNAMES VALUES(232,'mercury','mercury cougar brougham');
INSERT INTO CARNAMES VALUES(233,'chevrolet','chevrolet concours');
INSERT INTO CARNAMES VALUES(234,'buick','buick skylark');
INSERT INTO CARNAMES VALUES(235,'plymouth','plymouth volare custom');
INSERT INTO CARNAMES VALUES(236,'ford','ford granada');
INSERT INTO CARNAMES VALUES(237,'pontiac','pontiac grand prix lj');
INSERT INTO CARNAMES VALUES(238,'chevrolet','chevrolet monte carlo landau');
INSERT INTO CARNAMES VALUES(239,'chrysler','chrysler cordoba');
INSERT INTO CARNAMES VALUES(240,'ford','ford thunderbird');
INSERT INTO CARNAMES VALUES(241,'volkswagen','volkswagen rabbit custom');
INSERT INTO CARNAMES VALUES(242,'pontiac','pontiac sunbird coupe');
INSERT INTO CARNAMES VALUES(243,'toyota','toyota corolla liftback');
INSERT INTO CARNAMES VALUES(244,'ford','ford mustang ii 2+2');
INSERT INTO CARNAMES VALUES(245,'chevrolet','chevrolet chevette');
INSERT INTO CARNAMES VALUES(246,'dodge','dodge colt m/m');
INSERT INTO CARNAMES VALUES(247,'subaru','subaru dl');
INSERT INTO CARNAMES VALUES(248,'volkswagen','volkswagen dasher');
INSERT INTO CARNAMES VALUES(249,'datsun','datsun 810');
INSERT INTO CARNAMES VALUES(250,'bmw','bmw 320i');
INSERT INTO CARNAMES VALUES(251,'mazda','mazda rx-4');
INSERT INTO CARNAMES VALUES(252,'volkswagen','volkswagen rabbit custom diesel');
INSERT INTO CARNAMES VALUES(253,'ford','ford fiesta');
INSERT INTO CARNAMES VALUES(254,'mazda','mazda glc deluxe');
INSERT INTO CARNAMES VALUES(255,'datsun','datsun b210 gx');
INSERT INTO CARNAMES VALUES(256,'honda','honda civic cvcc');
INSERT INTO CARNAMES VALUES(257,'oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO CARNAMES VALUES(258,'dodge','dodge diplomat');
INSERT INTO CARNAMES VALUES(259,'mercury','mercury monarch ghia');
INSERT INTO CARNAMES VALUES(260,'pontiac','pontiac phoenix lj');
INSERT INTO CARNAMES VALUES(261,'chevrolet','chevrolet malibu');
INSERT INTO CARNAMES VALUES(262,'ford','ford fairmont (auto)');
INSERT INTO CARNAMES VALUES(263,'ford','ford fairmont (man)');
INSERT INTO CARNAMES VALUES(264,'plymouth','plymouth volare');
INSERT INTO CARNAMES VALUES(265,'amc','amc concord');
INSERT INTO CARNAMES VALUES(266,'buick','buick century special');
INSERT INTO CARNAMES VALUES(267,'mercury','mercury zephyr');
INSERT INTO CARNAMES VALUES(268,'dodge','dodge aspen');
INSERT INTO CARNAMES VALUES(269,'amc','amc concord d/l');
INSERT INTO CARNAMES VALUES(270,'chevrolet','chevrolet monte carlo landau');
INSERT INTO CARNAMES VALUES(271,'buick','buick regal sport coupe (turbo)');
INSERT INTO CARNAMES VALUES(272,'ford','ford futura');
INSERT INTO CARNAMES VALUES(273,'dodge','dodge magnum xe');
INSERT INTO CARNAMES VALUES(274,'chevrolet','chevrolet chevette');
INSERT INTO CARNAMES VALUES(275,'toyota','toyota corona');
INSERT INTO CARNAMES VALUES(276,'datsun','datsun 510');
INSERT INTO CARNAMES VALUES(277,'dodge','dodge omni');
INSERT INTO CARNAMES VALUES(278,'toyota','toyota celica gt liftback');
INSERT INTO CARNAMES VALUES(279,'plymouth','plymouth sapporo');
INSERT INTO CARNAMES VALUES(280,'oldsmobile','oldsmobile starfire sx');
INSERT INTO CARNAMES VALUES(281,'datsun','datsun 200-sx');
INSERT INTO CARNAMES VALUES(282,'audi','audi 5000');
INSERT INTO CARNAMES VALUES(283,'volvo','volvo 264gl');
INSERT INTO CARNAMES VALUES(284,'saab','saab 99gle');
INSERT INTO CARNAMES VALUES(285,'peugeot','peugeot 604sl');
INSERT INTO CARNAMES VALUES(286,'volkswagen','volkswagen scirocco');
INSERT INTO CARNAMES VALUES(287,'honda','honda accord lx');
INSERT INTO CARNAMES VALUES(288,'pontiac','pontiac lemans v6');
INSERT INTO CARNAMES VALUES(289,'mercury','mercury zephyr 6');
INSERT INTO CARNAMES VALUES(290,'ford','ford fairmont 4');
INSERT INTO CARNAMES VALUES(291,'amc','amc concord dl 6');
INSERT INTO CARNAMES VALUES(292,'dodge','dodge aspen 6');
INSERT INTO CARNAMES VALUES(293,'chevrolet','chevrolet caprice classic');
INSERT INTO CARNAMES VALUES(294,'ford','ford ltd landau');
INSERT INTO CARNAMES VALUES(295,'mercury','mercury grand marquis');
INSERT INTO CARNAMES VALUES(296,'dodge','dodge st. regis');
INSERT INTO CARNAMES VALUES(297,'buick','buick estate wagon (sw)');
INSERT INTO CARNAMES VALUES(298,'ford','ford country squire (sw)');
INSERT INTO CARNAMES VALUES(299,'chevrolet','chevrolet malibu classic (sw)');
INSERT INTO CARNAMES VALUES(300,'chrysler','chrysler lebaron town @ country (sw)');
INSERT INTO CARNAMES VALUES(301,'volkswagen','vw rabbit custom');
INSERT INTO CARNAMES VALUES(302,'mazda', 'mazda glc deluxe');
INSERT INTO CARNAMES VALUES(303,'dodge','dodge colt hatchback custom');
INSERT INTO CARNAMES VALUES(304,'amc','amc spirit dl');
INSERT INTO CARNAMES VALUES(305,'mercedes','mercedes benz 300d');
INSERT INTO CARNAMES VALUES(306,'cadillac','cadillac eldorado');
INSERT INTO CARNAMES VALUES(307,'peugeot','peugeot 504');
INSERT INTO CARNAMES VALUES(308,'oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO CARNAMES VALUES(309,'plymouth','plymouth horizon');
INSERT INTO CARNAMES VALUES(310,'plymouth','plymouth horizon tc3');
INSERT INTO CARNAMES VALUES(311,'datsun','datsun 210');
INSERT INTO CARNAMES VALUES(312,'fiat','fiat strada custom');
INSERT INTO CARNAMES VALUES(313,'buick','buick skylark limited');
INSERT INTO CARNAMES VALUES(314,'chevrolet','chevrolet citation');
INSERT INTO CARNAMES VALUES(315,'oldsmobile','oldsmobile omega brougham');
INSERT INTO CARNAMES VALUES(316,'pontiac','pontiac phoenix');
INSERT INTO CARNAMES VALUES(317,'volkswagen','vw rabbit');
INSERT INTO CARNAMES VALUES(318,'toyota','toyota corolla tercel');
INSERT INTO CARNAMES VALUES(319,'chevrolet','chevrolet chevette');
INSERT INTO CARNAMES VALUES(320,'datsun','datsun 310');
INSERT INTO CARNAMES VALUES(321,'chevrolet','chevrolet citation');
INSERT INTO CARNAMES VALUES(322,'ford','ford fairmont');
INSERT INTO CARNAMES VALUES(323,'amc','amc concord');
INSERT INTO CARNAMES VALUES(324,'dodge','dodge aspen');
INSERT INTO CARNAMES VALUES(325,'audi','audi 4000');
INSERT INTO CARNAMES VALUES(326,'toyota','toyota corona liftback');
INSERT INTO CARNAMES VALUES(327,'mazda','mazda 626');
INSERT INTO CARNAMES VALUES(328,'datsun','datsun 510 hatchback');
INSERT INTO CARNAMES VALUES(329,'toyota','toyota corolla');
INSERT INTO CARNAMES VALUES(330,'mazda','mazda glc');
INSERT INTO CARNAMES VALUES(331,'dodge','dodge colt');
INSERT INTO CARNAMES VALUES(332,'datsun','datsun 210');
INSERT INTO CARNAMES VALUES(333,'volkswagen','vw rabbit c (diesel)');
INSERT INTO CARNAMES VALUES(334,'volkswagen','vw dasher (diesel)');
INSERT INTO CARNAMES VALUES(335,'audi','audi 5000s (diesel)');
INSERT INTO CARNAMES VALUES(336,'mercedes-benz','mercedes-benz 240d');
INSERT INTO CARNAMES VALUES(337,'honda','honda civic 1500 gl');
INSERT INTO CARNAMES VALUES(338,'renault','renault lecar deluxe');
INSERT INTO CARNAMES VALUES(339,'subaru','subaru dl');
INSERT INTO CARNAMES VALUES(340, 'volkswagen','volkswagen rabbit');
INSERT INTO CARNAMES VALUES(341,'datsun','datsun 280-zx');
INSERT INTO CARNAMES VALUES(342,'mazda','mazda rx-7 gs');
INSERT INTO CARNAMES VALUES(343,'triumph','triumph tr7 coupe');
INSERT INTO CARNAMES VALUES(344,'ford','ford mustang cobra');
INSERT INTO CARNAMES VALUES(345,'honda','honda accord');
INSERT INTO CARNAMES VALUES(346,'plymouth','plymouth reliant');
INSERT INTO CARNAMES VALUES(347,'buick','buick skylark');
INSERT INTO CARNAMES VALUES(348,'dodge','dodge aries wagon (sw)');
INSERT INTO CARNAMES VALUES(349,'chevrolet','chevrolet citation');
INSERT INTO CARNAMES VALUES(350,'plymouth','plymouth reliant');
INSERT INTO CARNAMES VALUES(351,'toyota','toyota starlet');
INSERT INTO CARNAMES VALUES(352,'plymouth','plymouth champ');
INSERT INTO CARNAMES VALUES(353,'honda','honda civic 1300');
INSERT INTO CARNAMES VALUES(354,'subaru','subaru');
INSERT INTO CARNAMES VALUES(355,'datsun','datsun 210 mpg');
INSERT INTO CARNAMES VALUES(356,'toyota','toyota tercel');
INSERT INTO CARNAMES VALUES(357,'mazda','mazda glc 4');
INSERT INTO CARNAMES VALUES(358,'plymouth','plymouth horizon 4');
INSERT INTO CARNAMES VALUES(359,'ford','ford escort 4w');
INSERT INTO CARNAMES VALUES(360,'ford','ford escort 2h');
INSERT INTO CARNAMES VALUES(361,'volkswagen','volkswagen jetta');
INSERT INTO CARNAMES VALUES(362,'renault','renault 18i');
INSERT INTO CARNAMES VALUES(363,'honda','honda prelude');
INSERT INTO CARNAMES VALUES(364,'toyota','toyota corolla');
INSERT INTO CARNAMES VALUES(365,'datsun','datsun 200sx');
INSERT INTO CARNAMES VALUES(366,'mazda','mazda 626');
INSERT INTO CARNAMES VALUES(367,'peugeot','peugeot 505s turbo diesel');
INSERT INTO CARNAMES VALUES(368,'saab','saab 900s');
INSERT INTO CARNAMES VALUES(369,'volvo','volvo diesel');
INSERT INTO CARNAMES VALUES(370,'toyota','toyota cressida');
INSERT INTO CARNAMES VALUES(371,'datsun','datsun 810 maxima');
INSERT INTO CARNAMES VALUES(372,'buick','buick century');
INSERT INTO CARNAMES VALUES(373,'oldsmobile','oldsmobile cutlass ls');
INSERT INTO CARNAMES VALUES(374,'ford','ford granada gl');
INSERT INTO CARNAMES VALUES(375,'chrysler','chrysler lebaron salon');
INSERT INTO CARNAMES VALUES(376,'chevrolet','chevrolet cavalier');
INSERT INTO CARNAMES VALUES(377,'chevrolet','chevrolet cavalier wagon');
INSERT INTO CARNAMES VALUES(378,'chevrolet','chevrolet cavalier 2-door');
INSERT INTO CARNAMES VALUES(379,'pontiac','pontiac j2000 se hatchback');
INSERT INTO CARNAMES VALUES(380,'dodge','dodge aries se');
INSERT INTO CARNAMES VALUES(381,'pontiac','pontiac phoenix');
INSERT INTO CARNAMES VALUES(382,'ford','ford fairmont futura');
INSERT INTO CARNAMES VALUES(383,'amc','amc concord dl');
INSERT INTO CARNAMES VALUES(384,'volkswagen','volkswagen rabbit l');
INSERT INTO CARNAMES VALUES(385,'mazda','mazda glc custom l');
INSERT INTO CARNAMES VALUES(386,'mazda','mazda glc custom');
INSERT INTO CARNAMES VALUES(387,'plymouth','plymouth horizon miser');
INSERT INTO CARNAMES VALUES(388,'mercury','mercury lynx l');
INSERT INTO CARNAMES VALUES(389,'nissan','nissan stanza xe');
INSERT INTO CARNAMES VALUES(390,'honda','honda accord');
INSERT INTO CARNAMES VALUES(391,'toyota','toyota corolla');
INSERT INTO CARNAMES VALUES(392,'honda','honda civic');
INSERT INTO CARNAMES VALUES(393,'honda','honda civic (auto)');
INSERT INTO CARNAMES VALUES(394,'datsun','datsun 310 gx');
INSERT INTO CARNAMES VALUES(395,'buick','buick century limited');
INSERT INTO CARNAMES VALUES(396,'oldsmobile','oldsmobile cutlass ciera (diesel)');
INSERT INTO CARNAMES VALUES(397,'chrysler','chrysler lebaron medallion');
INSERT INTO CARNAMES VALUES(398,'ford','ford granada l');
INSERT INTO CARNAMES VALUES(399,'toyota','toyota celica gt');
INSERT INTO CARNAMES VALUES(400,'dodge','dodge charger 2.2');
INSERT INTO CARNAMES VALUES(401,'chevrolet','chevrolet camaro');
INSERT INTO CARNAMES VALUES(402,'ford','ford mustang gl');
INSERT INTO CARNAMES VALUES(403,'volkswagen','vw pickup');
INSERT INTO CARNAMES VALUES(404,'dodge','dodge rampage');
INSERT INTO CARNAMES VALUES(405,'ford','ford ranger');
INSERT INTO CARNAMES VALUES(406,'chevrolet','chevy s-10');
