-- Spencer Schurk, Jackson Goyette
-- sschurk@calpoly.edu, jgoyette@calpoly.edu

CREATE TABLE LIST(
    LASTNAME CHAR(30),
    FIRSTNAME CHAR(30),
    GRADE INTEGER,
    CLASSROOM INTEGER REFERENCES TEACHERS(CLASSROOM),
    PRIMARY KEY (LASTNAME, FIRSTNAME)
);

CREATE TABLE TEACHERS(
    LASTNAME CHAR(30),
    FIRSTNAME CHAR(30),
    CLASSROOM INTEGER REFERENCES LIST(CLASSROOM),
    PRIMARY KEY (LASTNAME, FIRSTNAME)
);