-- Spencer Schurk
-- sschurk@calpoly.edu

CREATE TABLE LIST(
    LASTNAME CHAR(30),
    FIRSTNAME CHAR(30),
    GRADE INTEGER,
    CLASSROOM INTEGER REFERENCES TEACHERS(CLASSROOM)
);

CREATE TABLE TEACHERS(
    LASTNAME CHAR(30),
    FIRSTNAME CHAR(30),
    CLASSROOM INTEGER REFERENCES LIST(CLASSROOM)
);