-- Jackson Goyette, Spencer Schurk
-- Lab 2, CSC 365, CARS dataset

CREATE TABLE CARMAKERS(
	ID INTEGER PRIMARY KEY,
	MAKER CHAR(30),
	FULLNAME CHAR(30),
	COUNTRY INTEGER REFERENCES COUNTRIES(COUNTRYID));

CREATE TABLE CARNAMES(
	MAKEID INTEGER PRIMARY KEY,
	MODEL CHAR(30) REFERENCES MODELLIST(MODEL),
	MAKEDESCRIPTION CHAR(60));

CREATE TABLE CARSDATA(
	ID INT PRIMARY KEY REFERENCES CARNAMES(MAKEID),
	MPG FLOAT,
	CYLINDERS INT,
	EDISPL FLOAT,
	HORSEPOWER FLOAT,
	WEIGHT FLOAT,
	ACCELERATE FLOAT,
	YEAR INT);

CREATE TABLE CONTINENTS(
	CONTID INT PRIMARY KEY,
	CONTINENT CHAR(30));

CREATE TABLE COUNTRIES(
	COUNTRYID INT PRIMARY KEY,
	COUNTRYNAME CHAR(30),
	CONTINENT INT REFERENCES CONTINENTS(CONTID));

CREATE TABLE MODELLIST(
	MODELID INT PRIMARY KEY,
	MAKER INT REFERENCES CARMAKERS(ID),
	MODEL CHAR(30));
