-- Jack Goyette, Spencer Schurk
-- jgoyette@calpoly.edu, sschurk@calpoly.edu


-- 
DELETE FROM CARSDATA
WHERE NOT ((YEAR=(1979 OR 1980) AND MPG >= 20) 
OR ((MPG >=26) AND HORSEPOWER > 110 )
OR ((CYLINDERS = 8) AND ACCELERATE < 10));

SELECT * FROM CARSDATA ORDER BY YEAR, ID;

ALTER TABLE CARSDATA DROP COLUMN EDISPL;
ALTER TABLE CARSDATA DROP COLUMN HORSEPOWER;
ALTER TABLE CARSDATA DROP COLUMN WEIGHT;


DELETE FROM CARSDATA
WHERE (CYLINDERS < 6);

SELECT * FROM CARSDATA ORDER BY YEAR, ID;
