-- Jack Goyette, Spencer Schurk
-- jgoyette@calpoly.edu, sschurk@calpoly.edu


INSERT INTO MODELLIST VALUES(1,1,'amc');
INSERT INTO MODELLIST VALUES(2,2,'audi');
INSERT INTO MODELLIST VALUES(3,3,'bmw');
INSERT INTO MODELLIST VALUES(4,4,'buick');
INSERT INTO MODELLIST VALUES(5,4,'cadillac');
INSERT INTO MODELLIST VALUES(6,5,'capri');
INSERT INTO MODELLIST VALUES(7,4,'chevrolet');
INSERT INTO MODELLIST VALUES(8,6,'chrysler');
INSERT INTO MODELLIST VALUES(9,7,'citroen');
INSERT INTO MODELLIST VALUES(10,8,'datsun');
INSERT INTO MODELLIST VALUES(11,6,'dodge');
INSERT INTO MODELLIST VALUES(12,9,'fiat');
INSERT INTO MODELLIST VALUES(13,5,'ford');
INSERT INTO MODELLIST VALUES(14,10,'hi');
INSERT INTO MODELLIST VALUES(15,11,'honda');
INSERT INTO MODELLIST VALUES(16,12,'mazda');
INSERT INTO MODELLIST VALUES(17,13,'mercedes');
INSERT INTO MODELLIST VALUES(18,13,'mercedes-benz');
INSERT INTO MODELLIST VALUES(19,5,'mercury');
INSERT INTO MODELLIST VALUES(20,8,'nissan');
INSERT INTO MODELLIST VALUES(21,4,'oldsmobile');
INSERT INTO MODELLIST VALUES(22,14,'opel');
INSERT INTO MODELLIST VALUES(23,15,'peugeot');
INSERT INTO MODELLIST VALUES(24,6,'plymouth');
INSERT INTO MODELLIST VALUES(25,4,'pontiac');
INSERT INTO MODELLIST VALUES(26,16,'renault');
INSERT INTO MODELLIST VALUES(27,17,'saab');
INSERT INTO MODELLIST VALUES(28,18,'subaru');
INSERT INTO MODELLIST VALUES(29,19,'toyota');
INSERT INTO MODELLIST VALUES(30,20,'triumph');
INSERT INTO MODELLIST VALUES(31,2,'volkswagen');
INSERT INTO MODELLIST VALUES(32,21,'volvo');
INSERT INTO MODELLIST VALUES(33,22,'kia');
INSERT INTO MODELLIST VALUES(34,23,'hyundai');
INSERT INTO MODELLIST VALUES(35,6,'jeep');
INSERT INTO MODELLIST VALUES(36,19,'scion');
